// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PrettyWoman.Infrastructure.Persistence;

#nullable disable

namespace PrettyWoman.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260608032654_PaymentsAndDeliveries")]
    partial class PaymentsAndDeliveries
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_roles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_role_claims");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_role_claims_role_id");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_claims_user_id");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_asp_net_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_logins_user_id");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<string>("RoleId")
                        .HasColumnType("text")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_asp_net_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_user_roles_role_id");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_asp_net_user_tokens");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PrettyWoman.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_categories");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("PrettyWoman.Domain.Entities.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("BlockedReason")
                        .HasColumnType("text")
                        .HasColumnName("blocked_reason");

                    b.Property<string>("Comments")
                        .HasColumnType("text")
                        .HasColumnName("comments");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("InstagramUser")
                        .HasColumnType("text")
                        .HasColumnName("instagram_user");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_blocked");

                    b.Property<bool>("IsFriend")
                        .HasColumnType("boolean")
                        .HasColumnName("is_friend");

                    b.Property<DateTime>("LastPurchaseDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_purchase_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.HasKey("Id")
                        .HasName("pk_clients");

                    b.ToTable("clients", (string)null);
                });

            modelBuilder.Entity("PrettyWoman.Domain.Entities.DeliveryAgency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.HasKey("Id")
                        .HasName("pk_delivery_agencies");

                    b.ToTable("delivery_agencies", (string)null);
                });

            modelBuilder.Entity("PrettyWoman.Domain.Entities.DeliveryStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_delivery_statuses");

                    b.ToTable("delivery_statuses", (string)null);
                });

            modelBuilder.Entity("PrettyWoman.Domain.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_departments");

                    b.ToTable("departments", (string)null);
                });

            modelBuilder.Entity("PrettyWoman.Domain.Entities.DiscountCampaign", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.HasKey("Id")
                        .HasName("pk_discount_campaigns");

                    b.ToTable("discount_campaigns", (string)null);
                });

            modelBuilder.Entity("PrettyWoman.Domain.Entities.DiscountCampaignProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DiscountCampaignId")
                        .HasColumnType("integer")
                        .HasColumnName("discount_campaign_id");

                    b.Property<int>("DiscountTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("discount_type_id");

                    b.Property<decimal>("DiscountValue")
                        .HasColumnType("numeric")
                        .HasColumnName("discount_value");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.HasKey("Id")
                        .HasName("pk_discount_campaign_products");

                    b.HasIndex("DiscountCampaignId")
                        .HasDatabaseName("ix_discount_campaign_products_discount_campaign_id");

                    b.HasIndex("DiscountTypeId")
                        .HasDatabaseName("ix_discount_campaign_products_discount_type_id");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_discount_campaign_products_product_id");

                    b.ToTable("discount_campaign_products", (string)null);
                });

            modelBuilder.Entity("PrettyWoman.Domain.Entities.DiscountSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_discount_sources");

                    b.ToTable("discount_sources", (string)null);
                });

            modelBuilder.Entity("PrettyWoman.Domain.Entities.DiscountType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_discount_types");

                    b.ToTable("discount_types", (string)null);
                });

            modelBuilder.Entity("PrettyWoman.Domain.Entities.Municipality", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer")
                        .HasColumnName("department_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_municipalities");

                    b.HasIndex("DepartmentId")
                        .HasDatabaseName("ix_municipalities_department_id");

                    b.ToTable("municipalities", (string)null);
                });

            modelBuilder.Entity("PrettyWoman.Domain.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<decimal>("AmountUsd")
                        .HasColumnType("numeric")
                        .HasColumnName("amount_usd");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("comments");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("OrderStatusId")
                        .HasColumnType("integer")
                        .HasColumnName("order_status_id");

                    b.Property<decimal>("ReceivedAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("received_amount");

                    b.Property<int>("SupplierId")
                        .HasColumnType("integer")
                        .HasColumnName("supplier_id");

                    b.Property<decimal>("TotalShippingCost")
                        .HasColumnType("numeric")
                        .HasColumnName("total_shipping_cost");

                    b.HasKey("Id")
                        .HasName("pk_orders");

                    b.HasIndex("OrderStatusId")
                        .HasDatabaseName("ix_orders_order_status_id");

                    b.HasIndex("SupplierId")
                        .HasDatabaseName("ix_orders_supplier_id");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("PrettyWoman.Domain.Entities.OrderStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_order_statuses");

                    b.ToTable("order_statuses", (string)null);
                });

            modelBuilder.Entity("PrettyWoman.Domain.Entities.OrderTrackingNumber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("integer")
                        .HasColumnName("order_id");

                    b.Property<int>("ProductReceiptId")
                        .HasColumnType("integer")
                        .HasColumnName("product_receipt_id");

                    b.Property<int>("ShippingCompanyId")
                        .HasColumnType("integer")
                        .HasColumnName("shipping_company_id");

                    b.Property<decimal>("ShippingCost")
                        .HasColumnType("numeric")
                        .HasColumnName("shipping_cost");

                    b.Property<DateTime?>("SupplierShipmentDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("supplier_shipment_date");

                    b.Property<string>("TrackingNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tracking_number");

                    b.Property<DateTime?>("WarehouseDeliveryDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("warehouse_delivery_date");

                    b.Property<decimal>("Weight")
                        .HasColumnType("numeric")
                        .HasColumnName("weight");

                    b.HasKey("Id")
                        .HasName("pk_order_tracking_numbers");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_order_tracking_numbers_order_id");

                    b.HasIndex("ProductReceiptId")
                        .HasDatabaseName("ix_order_tracking_numbers_product_receipt_id");

                    b.HasIndex("ShippingCompanyId")
                        .HasDatabaseName("ix_order_tracking_numbers_shipping_company_id");

                    b.ToTable("order_tracking_numbers", (string)null);
                });

            modelBuilder.Entity("PrettyWoman.Domain.Entities.PaymentMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_payment_methods");

                    b.ToTable("payment_methods", (string)null);
                });

            modelBuilder.Entity("PrettyWoman.Domain.Entities.PaymentTerminal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ComissionPercentage")
                        .HasColumnType("numeric")
                        .HasColumnName("comission_percentage");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_payment_terminals");

                    b.ToTable("payment_terminals", (string)null);
                });

            modelBuilder.Entity("PrettyWoman.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AvailableQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("available_quantity");

                    b.Property<string>("Color")
                        .HasColumnType("text")
                        .HasColumnName("color");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer")
                        .HasColumnName("order_id");

                    b.Property<int>("ProductDetailId")
                        .HasColumnType("integer")
                        .HasColumnName("product_detail_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<int>("ReceivedQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("received_quantity");

                    b.Property<int>("ReservedQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("reserved_quantity");

                    b.Property<decimal>("SalePrice")
                        .HasColumnType("numeric")
                        .HasColumnName("sale_price");

                    b.Property<int>("SizeId")
                        .HasColumnType("integer")
                        .HasColumnName("size_id");

                    b.Property<decimal>("UnitCost")
                        .HasColumnType("numeric")
                        .HasColumnName("unit_cost");

                    b.Property<decimal>("UnitCostWithShipping")
                        .HasColumnType("numeric")
                        .HasColumnName("unit_cost_with_shipping");

                    b.HasKey("Id")
                        .HasName("pk_products");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_products_order_id");

                    b.HasIndex("ProductDetailId")
                        .HasDatabaseName("ix_products_product_detail_id");

                    b.HasIndex("SizeId")
                        .HasDatabaseName("ix_products_size_id");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("PrettyWoman.Domain.Entities.ProductDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("SubcategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("subcategory_id");

                    b.Property<string>("SupplierProductCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("supplier_product_code");

                    b.HasKey("Id")
                        .HasName("pk_product_details");

                    b.HasIndex("SubcategoryId")
                        .HasDatabaseName("ix_product_details_subcategory_id");

                    b.ToTable("product_details", (string)null);
                });

            modelBuilder.Entity("PrettyWoman.Domain.Entities.ProductHold", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comments")
                        .HasColumnType("text")
                        .HasColumnName("comments");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("HoldReason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hold_reason");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<int?>("SaleId")
                        .HasColumnType("integer")
                        .HasColumnName("sale_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_product_holds");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_product_holds_product_id");

                    b.HasIndex("SaleId")
                        .HasDatabaseName("ix_product_holds_sale_id");

                    b.ToTable("product_holds", (string)null);
                });

            modelBuilder.Entity("PrettyWoman.Domain.Entities.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<int>("ProductDetailId")
                        .HasColumnType("integer")
                        .HasColumnName("product_detail_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_product_images");

                    b.HasIndex("ProductDetailId")
                        .HasDatabaseName("ix_product_images_product_detail_id");

                    b.ToTable("product_images", (string)null);
                });

            modelBuilder.Entity("PrettyWoman.Domain.Entities.ProductReceipt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ReceivedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_date");

                    b.HasKey("Id")
                        .HasName("pk_product_receipts");

                    b.ToTable("product_receipts", (string)null);
                });

            modelBuilder.Entity("PrettyWoman.Domain.Entities.ProductReceiptDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<int>("ProductReceiptId")
                        .HasColumnType("integer")
                        .HasColumnName("product_receipt_id");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric")
                        .HasColumnName("quantity");

                    b.HasKey("Id")
                        .HasName("pk_product_receipt_details");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_product_receipt_details_product_id");

                    b.HasIndex("ProductReceiptId")
                        .HasDatabaseName("ix_product_receipt_details_product_receipt_id");

                    b.ToTable("product_receipt_details", (string)null);
                });

            modelBuilder.Entity("PrettyWoman.Domain.Entities.Sale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClientId")
                        .HasColumnType("integer")
                        .HasColumnName("client_id");

                    b.Property<decimal>("Comission")
                        .HasColumnType("numeric")
                        .HasColumnName("comission");

                    b.Property<string>("Comments")
                        .HasColumnType("text")
                        .HasColumnName("comments");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("MunicipalityId")
                        .HasColumnType("integer")
                        .HasColumnName("municipality_id");

                    b.Property<int>("SaleChannelId")
                        .HasColumnType("integer")
                        .HasColumnName("sale_channel_id");

                    b.Property<int>("SaleStatusId")
                        .HasColumnType("integer")
                        .HasColumnName("sale_status_id");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("numeric")
                        .HasColumnName("sub_total");

                    b.Property<decimal>("SubtotalBeforeDiscount")
                        .HasColumnType("numeric")
                        .HasColumnName("subtotal_before_discount");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric")
                        .HasColumnName("total");

                    b.Property<decimal>("TotalDiscount")
                        .HasColumnType("numeric")
                        .HasColumnName("total_discount");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_sales");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_sales_client_id");

                    b.HasIndex("MunicipalityId")
                        .HasDatabaseName("ix_sales_municipality_id");

                    b.HasIndex("SaleChannelId")
                        .HasDatabaseName("ix_sales_sale_channel_id");

                    b.HasIndex("SaleStatusId")
                        .HasDatabaseName("ix_sales_sale_status_id");

                    b.ToTable("sales", (string)null);
                });

            modelBuilder.Entity("PrettyWoman.Domain.Entities.SaleChannel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_sale_channels");

                    b.ToTable("sale_channels", (string)null);
                });

            modelBuilder.Entity("PrettyWoman.Domain.Entities.SaleDelivery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AmountToCollect")
                        .HasColumnType("numeric")
                        .HasColumnName("amount_to_collect");

                    b.Property<int?>("ClientId")
                        .HasColumnType("integer")
                        .HasColumnName("client_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("Comments")
                        .HasColumnType("text")
                        .HasColumnName("comments");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DeliveryAgencyId")
                        .HasColumnType("integer")
                        .HasColumnName("delivery_agency_id");

                    b.Property<int>("DeliveryStatusId")
                        .HasColumnType("integer")
                        .HasColumnName("delivery_status_id");

                    b.Property<int>("MunicipalityId")
                        .HasColumnType("integer")
                        .HasColumnName("municipality_id");

                    b.Property<int>("SaleId")
                        .HasColumnType("integer")
                        .HasColumnName("sale_id");

                    b.Property<decimal>("ShippingChargedToClient")
                        .HasColumnType("numeric")
                        .HasColumnName("shipping_charged_to_client");

                    b.Property<decimal>("ShippingPaidToAgency")
                        .HasColumnType("numeric")
                        .HasColumnName("shipping_paid_to_agency");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_sale_deliveries");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_sale_deliveries_client_id");

                    b.HasIndex("DeliveryAgencyId")
                        .HasDatabaseName("ix_sale_deliveries_delivery_agency_id");

                    b.HasIndex("DeliveryStatusId")
                        .HasDatabaseName("ix_sale_deliveries_delivery_status_id");

                    b.HasIndex("MunicipalityId")
                        .HasDatabaseName("ix_sale_deliveries_municipality_id");

                    b.HasIndex("SaleId")
                        .HasDatabaseName("ix_sale_deliveries_sale_id");

                    b.ToTable("sale_deliveries", (string)null);
                });

            modelBuilder.Entity("PrettyWoman.Domain.Entities.SalePayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<decimal>("ComissionAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("comission_amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("NetReceivedAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("net_received_amount");

                    b.Property<int>("PaymentMethodId")
                        .HasColumnType("integer")
                        .HasColumnName("payment_method_id");

                    b.Property<int?>("PaymentTerminalId")
                        .HasColumnType("integer")
                        .HasColumnName("payment_terminal_id");

                    b.Property<int>("SaleId")
                        .HasColumnType("integer")
                        .HasColumnName("sale_id");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_sale_payments");

                    b.HasIndex("PaymentMethodId")
                        .HasDatabaseName("ix_sale_payments_payment_method_id");

                    b.HasIndex("PaymentTerminalId")
                        .HasDatabaseName("ix_sale_payments_payment_terminal_id");

                    b.HasIndex("SaleId")
                        .HasDatabaseName("ix_sale_payments_sale_id");

                    b.ToTable("sale_payments", (string)null);
                });

            modelBuilder.Entity("PrettyWoman.Domain.Entities.SaleProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CostAtSale")
                        .HasColumnType("numeric")
                        .HasColumnName("cost_at_sale");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("discount_amount");

                    b.Property<int?>("DiscountCampaignId")
                        .HasColumnType("integer")
                        .HasColumnName("discount_campaign_id");

                    b.Property<int>("DiscountSourceId")
                        .HasColumnType("integer")
                        .HasColumnName("discount_source_id");

                    b.Property<decimal>("FinalSalePrice")
                        .HasColumnType("numeric")
                        .HasColumnName("final_sale_price");

                    b.Property<decimal>("GrossProfit")
                        .HasColumnType("numeric")
                        .HasColumnName("gross_profit");

                    b.Property<decimal>("OriginalSalePrice")
                        .HasColumnType("numeric")
                        .HasColumnName("original_sale_price");

                    b.Property<decimal>("PaymentComission")
                        .HasColumnType("numeric")
                        .HasColumnName("payment_comission");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<int>("SaleId")
                        .HasColumnType("integer")
                        .HasColumnName("sale_id");

                    b.Property<int>("SaleProductStatusId")
                        .HasColumnType("integer")
                        .HasColumnName("sale_product_status_id");

                    b.HasKey("Id")
                        .HasName("pk_sale_products");

                    b.HasIndex("DiscountCampaignId")
                        .HasDatabaseName("ix_sale_products_discount_campaign_id");

                    b.HasIndex("DiscountSourceId")
                        .HasDatabaseName("ix_sale_products_discount_source_id");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_sale_products_product_id");

                    b.HasIndex("SaleId")
                        .HasDatabaseName("ix_sale_products_sale_id");

                    b.HasIndex("SaleProductStatusId")
                        .HasDatabaseName("ix_sale_products_sale_product_status_id");

                    b.ToTable("sale_products", (string)null);
                });

            modelBuilder.Entity("PrettyWoman.Domain.Entities.SaleProductStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_sale_product_statuses");

                    b.ToTable("sale_product_statuses", (string)null);
                });

            modelBuilder.Entity("PrettyWoman.Domain.Entities.SaleStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_sale_statuses");

                    b.ToTable("sale_statuses", (string)null);
                });

            modelBuilder.Entity("PrettyWoman.Domain.Entities.ShippingCompany", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Url")
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_shipping_companies");

                    b.ToTable("shipping_companies", (string)null);
                });

            modelBuilder.Entity("PrettyWoman.Domain.Entities.Size", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_sizes");

                    b.ToTable("sizes", (string)null);
                });

            modelBuilder.Entity("PrettyWoman.Domain.Entities.Subcategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_subcategories");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_subcategories_category_id");

                    b.ToTable("subcategories", (string)null);
                });

            modelBuilder.Entity("PrettyWoman.Domain.Entities.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_suppliers");

                    b.ToTable("suppliers", (string)null);
                });

            modelBuilder.Entity("PrettyWoman.Infrastructure.Persistence.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<string>("Lasname")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lasname");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_users");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_role_claims_asp_net_roles_role_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("PrettyWoman.Infrastructure.Persistence.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_claims_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("PrettyWoman.Infrastructure.Persistence.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_logins_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_roles_role_id");

                    b.HasOne("PrettyWoman.Infrastructure.Persistence.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("PrettyWoman.Infrastructure.Persistence.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_tokens_asp_net_users_user_id");
                });

            modelBuilder.Entity("PrettyWoman.Domain.Entities.DiscountCampaignProduct", b =>
                {
                    b.HasOne("PrettyWoman.Domain.Entities.DiscountCampaign", "DiscountCampaign")
                        .WithMany()
                        .HasForeignKey("DiscountCampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_discount_campaign_products_discount_campaigns_discount_camp");

                    b.HasOne("PrettyWoman.Domain.Entities.DiscountType", "DiscountType")
                        .WithMany()
                        .HasForeignKey("DiscountTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_discount_campaign_products_discount_types_discount_type_id");

                    b.HasOne("PrettyWoman.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_discount_campaign_products_products_product_id");

                    b.Navigation("DiscountCampaign");

                    b.Navigation("DiscountType");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("PrettyWoman.Domain.Entities.Municipality", b =>
                {
                    b.HasOne("PrettyWoman.Domain.Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_municipalities_departments_department_id");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("PrettyWoman.Domain.Entities.Order", b =>
                {
                    b.HasOne("PrettyWoman.Domain.Entities.OrderStatus", "OrderStatus")
                        .WithMany()
                        .HasForeignKey("OrderStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_orders_order_statuses_order_status_id");

                    b.HasOne("PrettyWoman.Domain.Entities.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_orders_suppliers_supplier_id");

                    b.Navigation("OrderStatus");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("PrettyWoman.Domain.Entities.OrderTrackingNumber", b =>
                {
                    b.HasOne("PrettyWoman.Domain.Entities.Order", "Order")
                        .WithMany("OrderTrackingNumbers")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_tracking_numbers_orders_order_id");

                    b.HasOne("PrettyWoman.Domain.Entities.ProductReceipt", "ProductReceipt")
                        .WithMany()
                        .HasForeignKey("ProductReceiptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_tracking_numbers_product_receipts_product_receipt_id");

                    b.HasOne("PrettyWoman.Domain.Entities.ShippingCompany", "ShippingCompany")
                        .WithMany()
                        .HasForeignKey("ShippingCompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_tracking_numbers_shipping_companies_shipping_company_");

                    b.Navigation("Order");

                    b.Navigation("ProductReceipt");

                    b.Navigation("ShippingCompany");
                });

            modelBuilder.Entity("PrettyWoman.Domain.Entities.Product", b =>
                {
                    b.HasOne("PrettyWoman.Domain.Entities.Order", "Order")
                        .WithMany("Products")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_products_orders_order_id");

                    b.HasOne("PrettyWoman.Domain.Entities.ProductDetail", "ProductDetail")
                        .WithMany()
                        .HasForeignKey("ProductDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_products_product_details_product_detail_id");

                    b.HasOne("PrettyWoman.Domain.Entities.Size", "Size")
                        .WithMany()
                        .HasForeignKey("SizeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_products_sizes_size_id");

                    b.Navigation("Order");

                    b.Navigation("ProductDetail");

                    b.Navigation("Size");
                });

            modelBuilder.Entity("PrettyWoman.Domain.Entities.ProductDetail", b =>
                {
                    b.HasOne("PrettyWoman.Domain.Entities.Subcategory", "Subcategory")
                        .WithMany("ProductDetails")
                        .HasForeignKey("SubcategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_details_subcategories_subcategory_id");

                    b.Navigation("Subcategory");
                });

            modelBuilder.Entity("PrettyWoman.Domain.Entities.ProductHold", b =>
                {
                    b.HasOne("PrettyWoman.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_holds_products_product_id");

                    b.HasOne("PrettyWoman.Domain.Entities.Sale", "Sale")
                        .WithMany()
                        .HasForeignKey("SaleId")
                        .HasConstraintName("fk_product_holds_sales_sale_id");

                    b.Navigation("Product");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("PrettyWoman.Domain.Entities.ProductImage", b =>
                {
                    b.HasOne("PrettyWoman.Domain.Entities.ProductDetail", "ProductDetail")
                        .WithMany()
                        .HasForeignKey("ProductDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_images_product_details_product_detail_id");

                    b.Navigation("ProductDetail");
                });

            modelBuilder.Entity("PrettyWoman.Domain.Entities.ProductReceiptDetail", b =>
                {
                    b.HasOne("PrettyWoman.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_receipt_details_products_product_id");

                    b.HasOne("PrettyWoman.Domain.Entities.ProductReceipt", "ProductReceipt")
                        .WithMany()
                        .HasForeignKey("ProductReceiptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_receipt_details_product_receipts_product_receipt_id");

                    b.Navigation("Product");

                    b.Navigation("ProductReceipt");
                });

            modelBuilder.Entity("PrettyWoman.Domain.Entities.Sale", b =>
                {
                    b.HasOne("PrettyWoman.Domain.Entities.Client", "Client")
                        .WithMany("Sales")
                        .HasForeignKey("ClientId")
                        .HasConstraintName("fk_sales_clients_client_id");

                    b.HasOne("PrettyWoman.Domain.Entities.Municipality", "Municipality")
                        .WithMany()
                        .HasForeignKey("MunicipalityId")
                        .HasConstraintName("fk_sales_municipalities_municipality_id");

                    b.HasOne("PrettyWoman.Domain.Entities.SaleChannel", "SaleChannel")
                        .WithMany()
                        .HasForeignKey("SaleChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sales_sale_channels_sale_channel_id");

                    b.HasOne("PrettyWoman.Domain.Entities.SaleStatus", "SaleStatus")
                        .WithMany()
                        .HasForeignKey("SaleStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sales_sale_statuses_sale_status_id");

                    b.Navigation("Client");

                    b.Navigation("Municipality");

                    b.Navigation("SaleChannel");

                    b.Navigation("SaleStatus");
                });

            modelBuilder.Entity("PrettyWoman.Domain.Entities.SaleDelivery", b =>
                {
                    b.HasOne("PrettyWoman.Domain.Entities.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .HasConstraintName("fk_sale_deliveries_clients_client_id");

                    b.HasOne("PrettyWoman.Domain.Entities.DeliveryAgency", "DeliveryAgency")
                        .WithMany()
                        .HasForeignKey("DeliveryAgencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sale_deliveries_delivery_agencies_delivery_agency_id");

                    b.HasOne("PrettyWoman.Domain.Entities.DeliveryStatus", "DeliveryStatus")
                        .WithMany()
                        .HasForeignKey("DeliveryStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sale_deliveries_delivery_statuses_delivery_status_id");

                    b.HasOne("PrettyWoman.Domain.Entities.Municipality", "Municipality")
                        .WithMany()
                        .HasForeignKey("MunicipalityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sale_deliveries_municipalities_municipality_id");

                    b.HasOne("PrettyWoman.Domain.Entities.Sale", "Sale")
                        .WithMany("Deliveries")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sale_deliveries_sales_sale_id");

                    b.Navigation("Client");

                    b.Navigation("DeliveryAgency");

                    b.Navigation("DeliveryStatus");

                    b.Navigation("Municipality");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("PrettyWoman.Domain.Entities.SalePayment", b =>
                {
                    b.HasOne("PrettyWoman.Domain.Entities.PaymentMethod", "PaymentMethod")
                        .WithMany()
                        .HasForeignKey("PaymentMethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sale_payments_payment_methods_payment_method_id");

                    b.HasOne("PrettyWoman.Domain.Entities.PaymentTerminal", "PaymentTerminal")
                        .WithMany()
                        .HasForeignKey("PaymentTerminalId")
                        .HasConstraintName("fk_sale_payments_payment_terminals_payment_terminal_id");

                    b.HasOne("PrettyWoman.Domain.Entities.Sale", "Sale")
                        .WithMany("Payments")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sale_payments_sales_sale_id");

                    b.Navigation("PaymentMethod");

                    b.Navigation("PaymentTerminal");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("PrettyWoman.Domain.Entities.SaleProduct", b =>
                {
                    b.HasOne("PrettyWoman.Domain.Entities.DiscountCampaign", "DiscountCampaign")
                        .WithMany()
                        .HasForeignKey("DiscountCampaignId")
                        .HasConstraintName("fk_sale_products_discount_campaigns_discount_campaign_id");

                    b.HasOne("PrettyWoman.Domain.Entities.DiscountSource", "DiscountSource")
                        .WithMany()
                        .HasForeignKey("DiscountSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sale_products_discount_sources_discount_source_id");

                    b.HasOne("PrettyWoman.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sale_products_products_product_id");

                    b.HasOne("PrettyWoman.Domain.Entities.Sale", "Sale")
                        .WithMany("Products")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sale_products_sales_sale_id");

                    b.HasOne("PrettyWoman.Domain.Entities.SaleProductStatus", "SaleProductStatus")
                        .WithMany()
                        .HasForeignKey("SaleProductStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sale_products_sale_product_statuses_sale_product_status_id");

                    b.Navigation("DiscountCampaign");

                    b.Navigation("DiscountSource");

                    b.Navigation("Product");

                    b.Navigation("Sale");

                    b.Navigation("SaleProductStatus");
                });

            modelBuilder.Entity("PrettyWoman.Domain.Entities.Subcategory", b =>
                {
                    b.HasOne("PrettyWoman.Domain.Entities.Category", "Category")
                        .WithMany("Subcategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_subcategories_categories_category_id");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("PrettyWoman.Domain.Entities.Category", b =>
                {
                    b.Navigation("Subcategories");
                });

            modelBuilder.Entity("PrettyWoman.Domain.Entities.Client", b =>
                {
                    b.Navigation("Sales");
                });

            modelBuilder.Entity("PrettyWoman.Domain.Entities.Order", b =>
                {
                    b.Navigation("OrderTrackingNumbers");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("PrettyWoman.Domain.Entities.Sale", b =>
                {
                    b.Navigation("Deliveries");

                    b.Navigation("Payments");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("PrettyWoman.Domain.Entities.Subcategory", b =>
                {
                    b.Navigation("ProductDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
